version: '3.7'

services:
  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
  backend:
    build: ./backend
    ports:
      - 5000:5000
  nginx:
    build: ./nginx
    ports:
      - 8080:8080